feat:added servictype page
JaseelaAlimahamed/ServiceConnectAdminUI pull request #43
Opened 2024-09-26 10:58 UTC by ebin-davis

2024-09-27 07:21 UTC, JaseelaAlimahamed commented on src/components/adminComponents/ServiceTypeComponent.jsx
make a folder inside adminComponent to set this file

2024-09-27 07:22 UTC, JaseelaAlimahamed commented on src/pages/adminPages/ServiceType.jsx
dont make this much code iin pages

2024-10-03 07:32 UTC, JaseelaAlimahamed requested changes
dont make too much lines in page , make it component and call it in pages,

2024-10-03 08:20 UTC, ebin-davis commented
completed the work

2024-10-03 13:09 UTC, merged