Create Franchisee Table
JaseelaAlimahamed/ServiceConnectAdminUI pull request #51
Opened 2024-10-07 17:45 UTC by vrindavnair

2024-10-09 13:47 UTC, JaseelaAlimahamed requested changes

2024-10-09 13:47 UTC, JaseelaAlimahamed commented on src/components/FranchiseComponents/FranchiceeReuseableComponents/FranchiseeCard.jsx
vrinda you are creationg admin page components then why did you save in franchise components.......
make the folder path like component/adminComponents/FanchiseManagement/franchiseeCard

2024-10-09 13:47 UTC, JaseelaAlimahamed commented on src/components/FranchiseComponents/FranchiceeReuseableComponents/FranchiseeIcons/Email.png
these are not components set these icons in assets or public file
assets/adminAssets/your file

2024-10-09 13:47 UTC, JaseelaAlimahamed commented on src/components/FranchiseComponents/FranchiceeReuseableComponents/FranchiseeTable.jsx
change path

2024-10-09 13:47 UTC, JaseelaAlimahamed commented on src/components/FranchiseComponents/FranchiseDetails/FranchiseeList.jsx
change path

2024-10-11 13:26 UTC, vrindavnair commented on src/components/FranchiseComponents/FranchiceeReuseableComponents/FranchiseeCard.jsx
Implemented as requeated

2024-10-11 13:26 UTC, vrindavnair commented on src/components/FranchiseComponents/FranchiceeReuseableComponents/FranchiseeIcons/Email.png
Implemented as requested

2024-10-11 13:27 UTC, vrindavnair commented on src/components/FranchiseComponents/FranchiceeReuseableComponents/FranchiseeTable.jsx
Implemented as requested

2024-10-11 13:27 UTC, vrindavnair commented on src/components/FranchiseComponents/FranchiseDetails/FranchiseeList.jsx
Implemented as requested

2024-10-12 21:55 UTC, merged